### ISSUE TITLE
Top Right Preset Off Screen

### ISSUE THREAD

**Issue by ellisonpatterson** [SamsidParty/TopNotify#29] opened 2024-09-13 16:32 UTC
I'm using a laptop, and using either top-right or top-left presets for the notification position has them off the screen.
I tried restarting, changing the resolution, and changing the scale to no avail.

Please let me know what other information I can provide and thank you for making this!

![Screenshot 2024-09-13 123018](https://github.com/user-attachments/assets/bca085e6-0ae7-4744-9cd0-ab9b557bc88f)
![Screenshot 2024-09-13 123111](https://github.com/user-attachments/assets/9c565b78-ab7b-407d-b098-505cf03c1c28)

**Comment by ellisonpatterson** [comment] 2024-09-13 16:45
> What scale is your laptop display set to? Is it fixed if you set it to 100%? Also, what version of TopNotify are you using?, this should have been fixed already.

I installed the Microsoft Store release, it says version 2.4.5. At scale 100% the same issue occurs.

**Comment by SamsidParty** [comment] 2024-09-13 16:52
Interesting, which build of win11 are you on?

**Comment by ellisonpatterson** [comment] 2024-09-13 16:55
Windows 11 Pro
OS Build: 22631.4169
Experience: Windows Feature Experience Pack 1000.22700.1034.0

It is a Lenovo laptop using their privacy guard driver for the monitor as well.

**Comment by SamsidParty** [comment] 2024-09-13 17:03
Let me update to 22631 and check

**Comment by SamsidParty** [comment] 2024-09-16 03:46
I still can't reproduce this issue, do custom positions still work?

**Comment by ellisonpatterson** [comment] 2024-09-16 17:34
The custom positions do work, and everything is working as expected on a separate monitor. I'm wondering why the laptop monitor is causing this issue.

Is there a way to provide logs about how it's calculating the boundaries?

**Comment by SamsidParty** [comment] 2024-09-16 18:13
TopNotify doesn't log info about calculations. I am currently busy until mid October so I will defer this issue until I am able to work on it more. Apologies for any inconvenience, hopefully the custom positions are enough for now.

**Comment by SamsidParty** [comment] 2024-10-12 10:24
Looks like the last update broke this, will be fixed in 2.4.6

**Closed** 2024-11-29 07:41 UTC
