### ISSUE TITLE
Can't open it, it keeps crashing

### ISSUE THREAD

**Issue by moony404** [SamsidParty/TopNotify#37] opened 2024-11-24 17:49 UTC
Hi,
Love the way that you can (I imagine) move notifications around, and I would like to have TopNotify, but it keeps crashing ! I see it in the taskbar (tray manager) for one second, and it despairs after that. I tried to see it in the task manager and I see it for 1 second as well as in the tray manager.
So if anyone know why, I would be happy to have some help !

**Comment by SamsidParty** [comment] 2024-11-24 17:53
Hi, we have received other reports of this crashing before and we are investigating.

For now, you can install the previous version of TopNotify [here](https://github.com/SamsidParty/TopNotify/releases/download/2.4.5/TopNotify.Msix) which doesn't have the crashing issues.

**Comment by SamsidParty** [comment] 2024-11-24 17:54
closing as duplicate of #36 , please check there for updates.

**Closed by SamsidParty** 2024-11-24 17:54 UTC
